-- CreateTable
CREATE TABLE "store_settings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "storeName" TEXT NOT NULL DEFAULT 'Café Store',
    "storeDescription" TEXT,
    "storeEmail" TEXT,
    "whatsappNumber" TEXT,
    "logoUrl" TEXT,
    "faviconUrl" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#f97316',
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "mercado_pago_public_key" TEXT,
    "mercado_pago_access_token" TEXT,
    "accept_pix" BOOLEAN NOT NULL DEFAULT true,
    "accept_credit_card" BOOLEAN NOT NULL DEFAULT true,
    "accept_boleto" BOOLEAN NOT NULL DEFAULT true,
    "accept_paypal" BOOLEAN NOT NULL DEFAULT false,
    "pix_expiration" TEXT NOT NULL DEFAULT '30min',
    "max_installments" INTEGER NOT NULL DEFAULT 12,
    "discount_on_cash" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "enable_free_shipping" BOOLEAN NOT NULL DEFAULT false,
    "free_shipping_amount" DECIMAL(10,2),
    "show_estimated_delivery" BOOLEAN NOT NULL DEFAULT true,
    "calculate_shipping" BOOLEAN NOT NULL DEFAULT true,
    "processing_days" INTEGER NOT NULL DEFAULT 1,
    "delivery_message" TEXT,
    "show_tracking" BOOLEAN NOT NULL DEFAULT true,
    "notify_new_order" BOOLEAN NOT NULL DEFAULT true,
    "notify_paid_order" BOOLEAN NOT NULL DEFAULT true,
    "notify_cancelled_order" BOOLEAN NOT NULL DEFAULT true,
    "notify_new_user" BOOLEAN NOT NULL DEFAULT true,
    "notify_new_feedback" BOOLEAN NOT NULL DEFAULT true,
    "notify_new_briefing" BOOLEAN NOT NULL DEFAULT true,
    "notify_low_stock" BOOLEAN NOT NULL DEFAULT true,
    "low_stock_threshold" INTEGER NOT NULL DEFAULT 5,
    "admin_emails" TEXT,
    "meta_title" TEXT,
    "meta_description" TEXT,
    "canonical_url" TEXT,
    "allow_indexing" BOOLEAN NOT NULL DEFAULT true,
    "google_analytics_id" TEXT,
    "facebook_pixel_id" TEXT,
    "sitemap_url" TEXT,
    "require_two_factor_admin" BOOLEAN NOT NULL DEFAULT false,
    "block_concurrent_sessions" BOOLEAN NOT NULL DEFAULT false,
    "session_expiration" TEXT NOT NULL DEFAULT '24h',
    "require_strong_password" BOOLEAN NOT NULL DEFAULT true,
    "show_announcement_banner" BOOLEAN NOT NULL DEFAULT true,
    "announcement_text" TEXT,
    "force_dark_mode" TEXT NOT NULL DEFAULT 'auto',
    "show_reviews_on_home" BOOLEAN NOT NULL DEFAULT true,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "store_settings_pkey" PRIMARY KEY ("id")
);
