<aside class="sticky glass rounded-2xl p-3.5 grid gap-2" style="top:calc(72px + 24px);">
    <span class="badge-amber w-fit">Admin</span>
    <a class="flex items-center justify-between min-h-[42px] rounded-[10px] px-3 font-black text-text-secondary transition-all duration-300 hover:bg-white/5 hover:text-text-primary" href="<?= url('admin/dashboard.php') ?>">Dashboard <span class="text-amber-glow">↗</span></a>
    <a class="flex items-center justify-between min-h-[42px] rounded-[10px] px-3 font-black text-text-secondary transition-all duration-300 hover:bg-white/5 hover:text-text-primary" href="<?= url('admin/products.php') ?>">Produtos <span class="text-text-muted">→</span></a>
    <a class="flex items-center justify-between min-h-[42px] rounded-[10px] px-3 font-black text-text-secondary transition-all duration-300 hover:bg-white/5 hover:text-text-primary" href="<?= url('admin/product-create.php') ?>">Novo produto <span class="text-amber-glow">+</span></a>
    <a class="flex items-center justify-between min-h-[42px] rounded-[10px] px-3 font-black text-text-secondary transition-all duration-300 hover:bg-white/5 hover:text-text-primary" href="<?= url('admin/orders.php') ?>">Pedidos <span class="text-text-muted">→</span></a>
    <a class="flex items-center justify-between min-h-[42px] rounded-[10px] px-3 font-black text-text-secondary transition-all duration-300 hover:bg-white/5 hover:text-text-primary" href="<?= url('admin/reviews.php') ?>">Avaliações <span class="text-text-muted">→</span></a>
    <a class="flex items-center justify-between min-h-[42px] rounded-[10px] px-3 font-black text-text-secondary transition-all duration-300 hover:bg-white/5 hover:text-text-primary" href="<?= url('admin/categories.php') ?>">Categorias <span class="text-text-muted">→</span></a>
    <a class="flex items-center justify-between min-h-[42px] rounded-[10px] px-3 font-black text-text-secondary transition-all duration-300 hover:bg-white/5 hover:text-text-primary" href="<?= url('admin/users.php') ?>">Usuarios <span class="text-text-muted">→</span></a>
    <a class="flex items-center justify-between min-h-[42px] rounded-[10px] px-3 font-black text-text-secondary transition-all duration-300 hover:bg-white/5 hover:text-text-primary" href="<?= url('index.php') ?>">Ver loja <span class="text-amber-glow">↗</span></a>
</aside>
